#!/usr/bin/python
# -*- coding: utf-8 -*-

UNCOMMON = '_UNCOMMON_'
PROPER_NOUN = '_PROPER_NOUN_'
CAPITALIZED = '_CAPITALIZED_'
PUNCTUATION = '_PUNCTUATION_'
TOKEN_TAG = 'TOKEN'
SENTENCE_START = '*'
SENTENCE_END = 'END'
TAG_CLASSES = ['PER', 'ORG', 'LOC', 'MISC']
TAG_NONE = 'O'
TAG_IN_PREFIX = 'I'
TAG_BOUNDARY_PREFIX = 'B'
UNCOMMON_LIMIT = 5
DEFAULT_NGRAM_CARDINALITY = 3
